networks:
  forumNetwork:
    driver: bridge

services:
  mariadb:
    image: mariadb:11.4.7
    restart: always
    env_file:
      - mariadb.env
    ports:
      - "3306:3306"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - forumNetwork

  forum_app:
    depends_on:
      - mariadb
    build:
      dockerfile: Dockerfile

    env_file:
      - src/.env
    ports:
      - "8080:8080"
    networks:
      - forumNetwork

volumes:
  mariadb_data:
